name: SkillScheme
version: 0.1
main: main.java.plugin.sirlich.SkillScheme
commands:
   ss:
     description: nothing here
     usage: nothying here
   server:
     description: yeah
     usage: yeah
   leave:
     description: yeah
     usage: ueah