loadouts:
  paladin:
    tokens: 15
    sword:
    - KillingSpree
    axe:
    - LeadAxe
    bow:
    - Shotgun
    special:
    - WrathOfJupiter
    passiveA: 
    - HolyStrike
    passiveB:
    - QualityClogs
  fighter:
    tokens: 15
    sword: []
    axe:
    - LeadAxe
    - RagingBull
    bow: []
    special:
    - Geronimo
    - BorimirsRevenge
    - StrikeTheEarth
    passiveA:
    - AxeOfPerun
    passiveB: []
  ranger:
    tokens: 15
    sword:
    - Deflection
    axe:
    - LeadAxe
    bow: []
    special:
    - ArcherTower
    passiveA:
    - BowOfShiva
    - StrongArm
    - MagmaBow
    - TripleShot
    passiveB:
    - QualityClogs
    - ElfSpeed
  rogue:
    tokens: 14
    sword:
    - BladeOfConfusion
    axe:
    - NimbleLeap
    bow:
    - PoisonDarts
    - PhantomArrows
    special:
    - EscapeArtist
    passiveA: 
    - SpeedBuff
    passiveB: 
    - QualityClogs
  warlock:
    tokens: 3
    sword:
    - CinderStrike
    axe:
    - ClassicFireball
    bow: []
    special:
    - Prism
    - IceRink
    passiveA: []
    passiveB:
    - QualityClogs















