cost: 1
max_level: 4
name: 'Arctic Armor'
description:
- '&7&oFreeze the world!'
- ""
- "Create an icy circle around you while active."
- "Good for mixing up the battlfield, and crossing water"
- ""
- "Radius: [radius] blocks"
- "Ice duration: [ice_duration / 20] seconds"
- "Mana Cost: [mana_loss_per_second] per second"
values:
  radius:
  - 4
  - 5
  - 10
  - 30
  ice_duration:
  - 100
  - 150
  - 200
  - 250
  mana_loss_per_second:
  - 10
  - 5
  - 4
  - 2
  mana_refresh_rate:
  - 10
  - 10
  - 10
  - 10
