cost: 1
maxLevel: 3
name: 'Axe of Perun'
description:
- '"&7&oWell, there is your place, remain there!"'
- ""
- "Land consecutive axe-hits without missing to"
- "become bloodlusted. Bloodlust deals extra damage."
- ""
- "Gain bloodlust after: [maxStack / 2] hits"
- "Must chain within: [cooldown / 20] seconds, or lose bloodlust"
- "Bonus damage: [bonusDamagePerHit / 2] hearts"
values:
  cooldown:
  - 60
  - 70
  - 80
  - 800
  maxStack:
  - 2
  - 3
  - 10
  - 200
  bonusDamagePerHit:
  - 0.1
  - 0.2
  - 0.3
  - 0.3
