cost: 2
max_level: 4
name: 'Barrage'
description:
- "Hold bown charge to channel."
- ""
- "Shoot a barrage of arrows,"
- "shoots extra arrows based on charge time."
- ""
- "Maximum Arrows: [max_charges]"
- "One arrow per: '[charge_refresh_rate / 20] seconds"
sounds:
  charge_tick_sound: "CLICK"
  charge_release_sound: "CLICK"
  charge_finish_sound: "PISTON_EXTEND"
  full_charge_release_sound: "ORB_PICKUP"
values:
  base_power:
  - 1
  - 1
  - 1
  - 1
  max_charges:
  - 5
  - 5
  - 5
  - 5
  charge_refresh_rate:
  - 10
  - 10
  - 10
  - 10
  cooldown:
  - 0
  - 0
  - 0
  - 0
