cost: 1
maxLevel: 3
name: 'Borimirs Revenge'
description:
- '&7&o"If by my life or death I can protect you, I will."'
- ""
- "While raging, enemy arrows deal 0 damage"
- "and 0 knockback."
- ""
- "Press &bF&8 to rage"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Duration: [duration / 20] seconds"
values:
  cooldown:
  - 200
  - 150
  - 100
  - 50
  duration:
  - 50
  - 100
  - 150
  - 200
