cost: 1
maxLevel: 3
name: 'Bow of Shiva'
description:
- '&7&o"Enough nonsense, Ravager! Time to die."'
- ""
- "Each arrow has a chance to chain on hit."
- "Arrows can chain multiple times."
- ""
- "Radius: [radius] blocks"
- "Chance: [chance * 100]%"
values:
  radius:
  - 10
  - 15
  - 20
  - 30
  velocity:
  - 2
  - 3
  - 5
  - 10
  chance:
  - 0.2
  - 0.3
  - 0.5
  - 1
