cost: 1
max_level: 3
name: 'Break Fall'
description:
- "Summon the power of well constructed"
- "footwear."
- ""
- "Passively reduce fall damage by [damage_reduction / 2] hearts."

values:
  damage_reduction:
  - 3
  - 4
  - 5
  - 6
