cost: 1
maxLevel: 3
name: 'Deflection'
description:
- '&7&o"Certain battles were won by retreating"'
- ""
- "Retreat from fights at high velocity"
- "by blocking melee attacks."
- ""
- "&bSword-Block&8 melee attacks to trigger"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Power: [power]"
values:
  cooldown:
  - 100
  - 400
  - 200
  - 200
  power:
  - 0.5
  - 0.7
  - 1.5
  - 6.3
