cost: 1
max_level: 3
name: 'Disengage'
description:
- "Retreat from fights at high velocity"
- "by blocking melee attacks."
- ""
- "&bSword-Block&8 melee attacks to trigger"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Power: [power]"
values:
  cooldown:
  - 500
  - 400
  - 200
  - 200
  power:
  - 6.5
  - 6.7
  - 6.5
  - 6.3
