cost: 1
maxLevel: 4
name: 'Elf Speed'
values:
  ticks:
  - 20
  - 30
  - 40
  - 50
  chargesNeeded:
  - 7
  - 6
  - 4
  - 2
  speedModifier:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  duration:
  - 2
  - 5
  - 8
  - 10
