cost: 1
max_level: 4
name: 'Entangle'
description:
- "Arrows deal slowness."
- ""
- "Slow: [slowness_amplifier] power"
- "For: [slowness_duration / 20] seconds"
values:
  slowness_duration:
  - 100
  - 400
  - 200
  - 800
  slowness_amplifier:
  - 2
  - 2
  - 2
  - 2
