cost: 1
maxLevel: 3
name: 'Lead Axe'
description:
- "Instantly disengage from sticky"
- "situations, by going back in time."
- ""
- "Press: &bF&8 to activate"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Time-travel: [ticks / 20] seconds into the past"
values:
  cooldown:
  - 100
  - 400
  - 200
  - 800
  ticks:
  - 40
  - 80
  - 100
  - 500
