cost: 1
max_level: 3
name: 'Fire Blast'
description:
- "Shoot fireballs. Classic."
- ""
- 'Right-Click &baxe&7 to fire'
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Yield: [yield] boom-units"
values:
  cooldown:
  - 100
  - 400
  - 200
  - 800
  yield:
  - 0.5
  - 0.2
  - 0.1
  - 0.3
