cost: 1
maxLevel: 3
name: 'Holy Strike'
description:
- '&7&o"I have no words. My voice is in my sword."'
- ""
- 'Each sword-strike has the chance'
- 'to deal massive knockback.'
- ''
- "Chance: [chance * 100]%"
- "Knockback: [knockback]"
values:
  chance:
  - 0.1
  - 0.5
  - .7
  - 1
  knockback:
  - 1
  - 2
  - 4
  - 9
