cost: 1
max_level: 4
name: 'Hunters Thrill'
description:
- "Land arrow shots to gain speed"
xliff:
  skill_expired: "Hunters Thrill has expired"
sounds:
  skill_expired: FIZZ
values:
  duration_on_hit:
  - 120
  - 120
  - 120
  - 120
  max_charges:
  - 4
  - 4
  - 4
  - 4
  minus_charges:
  - 1
  - 1
  - 1
  - 1
  ticking_skill_refresh_rate:
  - 1
  - 1
  - 1
  - 1
  base_millis:
  - 8000
  - 8000
  - 8000
  - 8000
  per_level_millis:
  - 1000
  - 2000
  - 3000
  - 4000
