cost: 1
max_level: 3
name: 'Ice Prison'
description:
- "&7&oMagic is stronger than steel!"
- ""
- "Retreat from the battlefield in this quick-deploy"
- "crystal prism."
- ""
- "Press &bF&8 to trigger"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Duration: [duration / 20] seconds"
values:
  cooldown:
  - 100
  - 400
  - 200
  - 800
  duration:
  - 50
  - 400
  - 700
  - 20
