cost: 1
max_level: 4
name: 'Incendiary Shot'
description:
- "Shoot an ignited arrow."
- ""
- "Left-Click &bbow&8 to prime"
- ""
- "Burn for: [burn_duration / 20] seconds"
- "Cooldown: [cooldown / 20] seconds"
values:
  cooldown:
  - 400
  - 350
  - 300
  - 250
  burn_duration:
  - 60
  - 60
  - 60
  - 60
