cost: 1
maxLevel: 4
name: 'Lead Axe'
description:
- "Bash enemies across the map with"
- "your 15-tonne lead axe."
- ""
- "Right-Click &baxe&8 to prime"
- "&bMelee-Attack&8 while primed to deal massive knockback"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Power: [power]"
values:
  cooldown:
  - 500
  - 400
  - 300
  - 200
  power:
  - 200
  - 3
  - 4
  - 5
