cost: 1
max_level: 3
name: 'Leap'
description:
- "Leap around the map at high speeds with"
- "this mobility focused skill."
- ""
- "Right-Click &baxe&8 to leap"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Power: [power]"
values:
  cooldown:
  - 100
  - 400
  - 200
  - 800
  power:
  - 2
  - 3
  - 4
  - 5
