
cost: 1
maxLevel: 4
name: 'Ice Rink'
refreshRate: 5
description:
- '&7&oFreeze the world!'
- ""
- "Create an icy circle around you while active."
- "Good for mixing up the battlfield, and crossing water"
- ""
- "Radius: [radius] blocks"
- "Ice duration: [iceDuration / 20] seconds"
- "Mana Cost: [manaLossPerSecond / 20] per second"
values:
  radius:
  - 4
  - 5
  - 10
  - 30
  iceDuration:
  - 100
  - 150
  - 200
  - 250
  manaLossPerSecond:
  - 40
  - 30
  - 20
  - 10
