cost: 1
max_level: 4
name: 'Pin Down'
description:
- "Left-Click &bbow&8 to instantly fire"
- "an arrow, which gives anybody hit"
- "Slowness IV for [slowness_duration / 20] seconds."
- ""
- "Cooldown: [cooldown / 20] seconds"
values:
  cooldown:
  - 500
  - 400
  - 300
  - 200
  slowness_duration:
  - 60
  - 60
  - 60
  - 60
  slowness_amplifier:
  - 4
  - 4
  - 4
  - 4
  arrow_velocity:
  - 1
  - 1
  - 1
  - 1
