cost: 1
maxLevel: 3
name: 'Raging Bull'
values:
  cooldown:
  - 70
  - 60
  - 50
  - 10
  duration:
  - 30
  - 40
  - 50
  - 60
  slownessDuration:
  - 10
  - 20
  - 40
  - 50
  slownessPower:
  - 0.4
  - 0.5
  - 0.5
  - 1
  speedPower:
  - 0.3
  - 0.4
  - 0.5
  - 0.6
