cost: 1
max_level: 4
name: 'Sharp Shooter'
description:
- "Chain arrows to deal bonus damage."
- ""
- "Bonus per hit: [bonus_damage_per_charge / 2] hearts"
- "Max charges: [max_charges]"
xliff:
  
sounds:
  on_miss: BURP
  on_hit: BAT_DEATH
values:
  bonus_damage_per_charge:
  - 2.0
  - 2.0
  - 2.0
  - 2.0
  max_charges:
  - 3
  - 4
  - 5
  - 6
  ticking_skill_refresh_rate:
  - 10
  - 10
  - 10
  - 10
  base_millis:
  - 8000
  - 8000
  - 8000
  - 8000
  per_level_millis:
  - 1000
  - 2000
  - 3000
  - 4000
