cost: 1
max_level: 4
name: 'Silencing Arrow'
description:
- "Primed arrows will silence enemies."
- "silenced enemies cannot use skills."
- ""
- "Left-Click &bbow&8 to prime"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Silence for: [silence_duration / 20] seconds"
xliff:
  you_are_now_silenced: "You are now silenced"
  you_are_no_longer_silenced: "You are no longer silenced"
sounds:
  you_are_now_silenced: ZOMBIE_HURT
  you_are_no_longer_silenced: ZOMBIE_HURT
values:
  cooldown:
  - 100
  - 400
  - 200
  - 800
  silence_duration:
  - 60
  - 60
  - 60
  - 60
