cost: 1
maxLevel: 4
name: 'Strike the Earth'
description:
- '&7&o"Insert line here"'
- ""
- "Strike the earth to knockback enemies"
- "within a radius."
- ""
- "Press &bF&8 to trigger"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Range: [range] blocks"
- "Power: [power]"
values:
  cooldown:
  - 100
  - 400
  - 200
  - 100
  range:
  - 5
  - 6
  - 7
  - 10
  power:
  - 0.4
  - 0.8
  - 1
  - 2
