cost: 1
maxLevel: 4
name: 'Strong Arm'
description:
- '&7&o"Mighty is the arm of Robinhood!"'
- ""
- "Fully-charged arrows go much quicker"
- "and travel further than normal."
- ""
- "Power: [power]"
values:
  power:
  - 0.2
  - 0.3
  - 0.5
  - 30.0
