cost: 2
max_level: 4
name: 'Wolf Pounce'
description:
- '&7&oThe sky is the limit!'
- ""
- "Block with sword to charge."
- "Release to leap a long distance."
sounds:
  charge_tick_sound: "ZOMBIE_HURT"
  charge_release_sound: "ZOMBIE_HURT"
  charge_finish_sound: "ZOMBIE_HURT"
  full_charge_release_sound: "ZOMBIE_HURT"
values:
  base_power:
  - 1
  - 1
  - 1
  - 1
  max_charges:
  - 5
  - 5
  - 5
  - 5
  charge_refresh_rate:
  - 4
  - 4
  - 4
  - 4
  cooldown:
  - 100
  - 400
  - 200
  - 100
