cost: 1
maxLevel: 4
name: 'Wrath Of Jupiter'
description:
- '&7&o"The gods fight for you!"'
- ""
- "Smite your enemies with thunderbolts."
- ""
- "Press &bF&8 to activate"
- ""
- "Cooldown: [cooldown / 20] seconds"
- "Range: [range] blocks"
- "Damage: [damageOnStrike / 2] hearts"
- "Burn: [fireTicks / 20] seconds"
values:
  cooldown:
  - 60
  - 70
  - 80
  - 800
  range:
  - 5
  - 7
  - 10
  - 15
  fireTicks:
  - 20
  - 40
  - 50
  - 100
  damageOnStrike:
  - 1
  - 2
  - 3
  - 50
